name: Muximux
description: |
   This is a lightweight portal to view & manage your HTPC apps without having to run anything more than a PHP enabled webserver. With Muximux you don't need to keep multiple tabs open, or bookmark the URL to all of your apps. Muximux.
version: 1.0
category: App
maintainer: # The maintainer of the catalog entry
license: # The license
projectURL: https://github.com/mescon/Muximux
